$axure.loadCurrentPage({
  "url":"近期活动.html",
  "generationDate":new Date(1407487647625.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5be7026f20fb47ff8ea40ff7d59b8bf6",
    "type":"Axure:Page",
    "name":"近期活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"66585a0eed8c4e668716e3f3b294a7af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1616,
              "height":1580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed40d9701f104ff892a480f109ea5418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1616,
                  "height":1580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/近期活动/u0.jpg"}},
{
          "id":"7e7e3cac914f45fea9df2b22c452088e",
          "label":"近期活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d060cd87f74d4f56843916ceec4c7bbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 近期活动",
                      "target":{
                        "targetType":"page",
                        "url":"近期活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"232220239e9c4ba8b29123133051a342",
          "label":"活动回顾",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd80090997264984a214a2b805b3b132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动回顾",
                      "target":{
                        "targetType":"page",
                        "url":"活动回顾.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c70c9407e852407fb43c724d5c00bcfe",
          "label":"放映间",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":658,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ec9c3ffe0441a9b99bfd354d1be405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":658,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 放映间",
                      "target":{
                        "targetType":"page",
                        "url":"放映间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e135fec1a134bdd825b4ed819e706c3",
          "label":"品牌活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e103a97c185b4989a77f6121cd657030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌活动",
                      "target":{
                        "targetType":"page",
                        "url":"品牌活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c45d7dc69bf540899fc52d7bb37e4b5d",
          "label":"投票专区",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":898,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72e93d7a8ca1452caf561e805f522ce5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":898,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 投票专区",
                      "target":{
                        "targetType":"page",
                        "url":"投票专区.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"218ddb3756234215a553fa490255aeb2",
          "label":"发布活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1212,
              "y":146},
            "size":{
              "width":90,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3af720e953748fba17a5759b3c01932",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1212,
                  "y":146},
                "size":{
                  "width":90,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布",
                      "target":{
                        "targetType":"page",
                        "url":"发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8a5f36cfcc04b9db75ce84cd5d96c6a",
          "label":"home",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":135},
            "size":{
              "width":56,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"081c0b2a74864a7680144d145d49662d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":135},
                "size":{
                  "width":56,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"622ac804cc0d48f3a53e1956c1fabcf2",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":420.000030517578,
              "y":370},
            "size":{
              "width":810,
              "height":930}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8989a6407b4542fb8f8bfdd7d08aec0a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5387f996cac44b8b8bd6329f5f6d6f6b",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":886,
                      "height":916}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb92f33e78904cca8f84cec13386d977",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":886,
                          "height":916}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/近期活动/u17.png"}},
{
                  "id":"48d128fe35654efd9c599a728fcd7e8a",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b520aa06d73493da3cc21151a40aeda",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to State1",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a6bda0b14dc44ad69458b58dfc67e67d",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":320,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae0ada2308a74b3dafaa861d63b41d26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":320,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d77ec4d6e1564f7aa69b6cf4ea247b8e",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":360,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9942d0400996409797d2fcd51336e88d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":360,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"32bbbd31bf954ee58d960fbea4062779",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":30},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bff2bdb9a11e49478b34af2d56815a49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":30},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7ab70e1ef58e419c8d845df5fdb3d3b2",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":330.5,
                      "y":30},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"369c5cd868924135bf9d293e469ab2c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":330.5,
                          "y":30},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"14b36dde3a854dc59038592d7ab09ea5",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":595,
                      "y":20},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4a1b37076ed4d2e8736cb6f4b326dce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":595,
                          "y":20},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"28eddf3979274ff087c471d002e08298",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":615,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff3f7c68d4744769839bbfbb1c209fd0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":615,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6c4c33d8bda145d1a8a36bde8f796f2e",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":320,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cff0734c19464f45a9c66f03946ef049",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":320,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"83b872680bb84863bd0cd0522e71d9d8",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5dbf6bba867342bd9980f170e63d4d70",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"afc082068b414b469a19d82fbcbb34a6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"73ab567248d24faa8b2f8f428b6bdcce",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":886,
                      "height":916}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"524b0182f73941fca8b77e69456ac9e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":886,
                          "height":916}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/近期活动/u37.png"}},
{
                  "id":"83974069818847c78fbd4bd605300815",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8ec9822a0b540c8b143b19af8e1b255",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to State1",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2df77cd0e75f4c5ebc420de55583109f",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":320,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a67d3c3b06ce447ca0d1830bb091b953",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":320,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2c6edc2d992742469d92a7c4dff9c81c",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":360,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c7823069bcb40a78eb30b849bd7f64b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":360,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c49bc7e24e254ce7ae5390f227398d98",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":30},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d5a5e3ffbad4967a311728795bc46d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":30},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"486a0fc53f2b4502b0d40dc088bf8cff",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":330.5,
                      "y":30},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9904c08b5faa441d8d81223e92e96911",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":330.5,
                          "y":30},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3ac67d98f0d47458c88d1afc5db45ae",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":595,
                      "y":20},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c4f7c1b407d45b69704cd99d263a8c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":595,
                          "y":20},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8810a12406264de2b65d229dca55595c",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":615,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc372d2620fe426cb8dafdbbeba65309",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":615,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a95efd6be379469a8e436fa8b66e9bfa",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":320,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48bb6c6ab76e47ebb7d64a14985fff6f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":320,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5fbd001d8c204990a5013a915460b3f3",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6905408ae08546e991b244d6c2031973",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"4826e18d394f4d04a3570e4c5afa3979",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2391dbafc74d4e48a8880d8309464080",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":886,
                      "height":916}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4bcf9e15956d41498300f4ffe5fbd714",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":886,
                          "height":916}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/近期活动/u57.png"}},
{
                  "id":"7b97c3bd80144e0f9e4f1f929c87ecce",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2fdc6b4806644c68801b428c7a89b23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to State1",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bc2a9d987e0a4759b9d802b37b80187c",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":320,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5c211b2deb84afda8c3affc0e8cd247",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":320,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"082a5e708f47421da8a73584f56193dd",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":360,
                      "y":860},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97056cc8bac14cfb8fb4e991bf66ec82",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":360,
                          "y":860},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 (动态面板) to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["622ac804cc0d48f3a53e1956c1fabcf2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d14b5a67944d4473a5af097c8c583942",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":30},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dcf5386f97d34670a614b69925d70337",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":30},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2879caedb0394bd0adaa7a66ae29a123",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":330.5,
                      "y":30},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6cbbf917308e42d8870bf39bdc1f9285",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":330.5,
                          "y":30},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e5cbbc202cc24af8a4e5fc628f740af5",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":595,
                      "y":20},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9418b7e550cb4e0ea255899b8db5df2d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":595,
                          "y":20},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"16f669a6a2f6447b835ae8c30557285c",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":615,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"635a5858f5c74459ac90643af0ff3523",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":615,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"24fdd19fff084c0494b17e65ad8cfaf5",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":320,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5756254e99ed462487080c0701d03e73",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":320,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c658c3067bad4812bbccf38ec64079da",
                  "label":"",
                  "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":420},
                    "size":{
                      "width":225,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f2794fc67554a30b76eade11d071ec0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"622ac804cc0d48f3a53e1956c1fabcf2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":420},
                        "size":{
                          "width":225,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 具体活动页面",
                              "target":{
                                "targetType":"page",
                                "url":"具体活动页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"7022895d654d49f89346944d3451ebeb",
          "label":"登陆框",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1600},
            "size":{
              "width":1616,
              "height":3044}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d793faf520d145c38caa23f3120ccae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1600},
                "size":{
                  "width":1616,
                  "height":3044}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/登陆框_u102.png"}},
{
          "id":"2b7e5cb6a500432ab00d8c0be1de0131",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":660,
              "y":2068},
            "size":{
              "width":395,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"e56e46ec14eb44d0ac15438c9e5333ce",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":650,
              "y":2154.40014648438},
            "size":{
              "width":395,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"183518857561464e9187628145e2f47d",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":2260},
            "size":{
              "width":192,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3dbe51d56114a18bdfd69aeea5c5e62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":2260},
                "size":{
                  "width":192,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["7022895d654d49f89346944d3451ebeb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2b7e5cb6a500432ab00d8c0be1de0131"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e56e46ec14eb44d0ac15438c9e5333ce"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45f21bde638e4f719b3348cae9ef5601",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1152,
              "y":1970},
            "size":{
              "width":58,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aeed972eabf48de8f0bbe8c30231497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1152,
                  "y":1970},
                "size":{
                  "width":58,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["7022895d654d49f89346944d3451ebeb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["2b7e5cb6a500432ab00d8c0be1de0131"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e56e46ec14eb44d0ac15438c9e5333ce"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aefd88c34fc467486a0343f5fa8afe6",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1162,
              "y":146},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c10c978b337465eae38634f57d52f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1162,
                  "y":146},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["cd58bd81b8c847d99afbd7fde8743d95"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b5ed2e8ff9b14b24bc88fcfd7340ce18"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1075b67f5a5f4859adfa6226ba9a8840"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd58bd81b8c847d99afbd7fde8743d95",
          "label":"登陆框",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":1616,
              "height":3044},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fd4edc1944447c4b09dd4e1390a63f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":1616,
                  "height":3044},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/登陆框_u102.png"}},
{
          "id":"b5ed2e8ff9b14b24bc88fcfd7340ce18",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":660,
              "y":468},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"1075b67f5a5f4859adfa6226ba9a8840",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":650,
              "y":554},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"3e1071df2cc248d4bac15dac5963ff80",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":660},
            "size":{
              "width":192,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65c674bc395e4154a14840eac5abcac1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":660},
                "size":{
                  "width":192,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["cd58bd81b8c847d99afbd7fde8743d95"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b5ed2e8ff9b14b24bc88fcfd7340ce18"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1075b67f5a5f4859adfa6226ba9a8840"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"210dd600ef854768a5f1552c1b1f6f83",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1152,
              "y":370},
            "size":{
              "width":58,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21b745953f8846da9b2858b85140d311",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1152,
                  "y":370},
                "size":{
                  "width":58,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["cd58bd81b8c847d99afbd7fde8743d95"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b5ed2e8ff9b14b24bc88fcfd7340ce18"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1075b67f5a5f4859adfa6226ba9a8840"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "66585a0eed8c4e668716e3f3b294a7af":{
      "scriptId":"u0"},
    "ed40d9701f104ff892a480f109ea5418":{
      "scriptId":"u1"},
    "7e7e3cac914f45fea9df2b22c452088e":{
      "scriptId":"u2"},
    "d060cd87f74d4f56843916ceec4c7bbb":{
      "scriptId":"u3"},
    "232220239e9c4ba8b29123133051a342":{
      "scriptId":"u4"},
    "cd80090997264984a214a2b805b3b132":{
      "scriptId":"u5"},
    "c70c9407e852407fb43c724d5c00bcfe":{
      "scriptId":"u6"},
    "d5ec9c3ffe0441a9b99bfd354d1be405":{
      "scriptId":"u7"},
    "9e135fec1a134bdd825b4ed819e706c3":{
      "scriptId":"u8"},
    "e103a97c185b4989a77f6121cd657030":{
      "scriptId":"u9"},
    "c45d7dc69bf540899fc52d7bb37e4b5d":{
      "scriptId":"u10"},
    "72e93d7a8ca1452caf561e805f522ce5":{
      "scriptId":"u11"},
    "218ddb3756234215a553fa490255aeb2":{
      "scriptId":"u12"},
    "b3af720e953748fba17a5759b3c01932":{
      "scriptId":"u13"},
    "d8a5f36cfcc04b9db75ce84cd5d96c6a":{
      "scriptId":"u14"},
    "081c0b2a74864a7680144d145d49662d":{
      "scriptId":"u15"},
    "622ac804cc0d48f3a53e1956c1fabcf2":{
      "scriptId":"u16"},
    "5387f996cac44b8b8bd6329f5f6d6f6b":{
      "scriptId":"u17"},
    "eb92f33e78904cca8f84cec13386d977":{
      "scriptId":"u18"},
    "48d128fe35654efd9c599a728fcd7e8a":{
      "scriptId":"u19"},
    "5b520aa06d73493da3cc21151a40aeda":{
      "scriptId":"u20"},
    "a6bda0b14dc44ad69458b58dfc67e67d":{
      "scriptId":"u21"},
    "ae0ada2308a74b3dafaa861d63b41d26":{
      "scriptId":"u22"},
    "d77ec4d6e1564f7aa69b6cf4ea247b8e":{
      "scriptId":"u23"},
    "9942d0400996409797d2fcd51336e88d":{
      "scriptId":"u24"},
    "32bbbd31bf954ee58d960fbea4062779":{
      "scriptId":"u25"},
    "bff2bdb9a11e49478b34af2d56815a49":{
      "scriptId":"u26"},
    "7ab70e1ef58e419c8d845df5fdb3d3b2":{
      "scriptId":"u27"},
    "369c5cd868924135bf9d293e469ab2c6":{
      "scriptId":"u28"},
    "14b36dde3a854dc59038592d7ab09ea5":{
      "scriptId":"u29"},
    "e4a1b37076ed4d2e8736cb6f4b326dce":{
      "scriptId":"u30"},
    "28eddf3979274ff087c471d002e08298":{
      "scriptId":"u31"},
    "ff3f7c68d4744769839bbfbb1c209fd0":{
      "scriptId":"u32"},
    "6c4c33d8bda145d1a8a36bde8f796f2e":{
      "scriptId":"u33"},
    "cff0734c19464f45a9c66f03946ef049":{
      "scriptId":"u34"},
    "83b872680bb84863bd0cd0522e71d9d8":{
      "scriptId":"u35"},
    "5dbf6bba867342bd9980f170e63d4d70":{
      "scriptId":"u36"},
    "73ab567248d24faa8b2f8f428b6bdcce":{
      "scriptId":"u37"},
    "524b0182f73941fca8b77e69456ac9e0":{
      "scriptId":"u38"},
    "83974069818847c78fbd4bd605300815":{
      "scriptId":"u39"},
    "a8ec9822a0b540c8b143b19af8e1b255":{
      "scriptId":"u40"},
    "2df77cd0e75f4c5ebc420de55583109f":{
      "scriptId":"u41"},
    "a67d3c3b06ce447ca0d1830bb091b953":{
      "scriptId":"u42"},
    "2c6edc2d992742469d92a7c4dff9c81c":{
      "scriptId":"u43"},
    "7c7823069bcb40a78eb30b849bd7f64b":{
      "scriptId":"u44"},
    "c49bc7e24e254ce7ae5390f227398d98":{
      "scriptId":"u45"},
    "2d5a5e3ffbad4967a311728795bc46d1":{
      "scriptId":"u46"},
    "486a0fc53f2b4502b0d40dc088bf8cff":{
      "scriptId":"u47"},
    "9904c08b5faa441d8d81223e92e96911":{
      "scriptId":"u48"},
    "f3ac67d98f0d47458c88d1afc5db45ae":{
      "scriptId":"u49"},
    "9c4f7c1b407d45b69704cd99d263a8c0":{
      "scriptId":"u50"},
    "8810a12406264de2b65d229dca55595c":{
      "scriptId":"u51"},
    "fc372d2620fe426cb8dafdbbeba65309":{
      "scriptId":"u52"},
    "a95efd6be379469a8e436fa8b66e9bfa":{
      "scriptId":"u53"},
    "48bb6c6ab76e47ebb7d64a14985fff6f":{
      "scriptId":"u54"},
    "5fbd001d8c204990a5013a915460b3f3":{
      "scriptId":"u55"},
    "6905408ae08546e991b244d6c2031973":{
      "scriptId":"u56"},
    "2391dbafc74d4e48a8880d8309464080":{
      "scriptId":"u57"},
    "4bcf9e15956d41498300f4ffe5fbd714":{
      "scriptId":"u58"},
    "7b97c3bd80144e0f9e4f1f929c87ecce":{
      "scriptId":"u59"},
    "b2fdc6b4806644c68801b428c7a89b23":{
      "scriptId":"u60"},
    "bc2a9d987e0a4759b9d802b37b80187c":{
      "scriptId":"u61"},
    "f5c211b2deb84afda8c3affc0e8cd247":{
      "scriptId":"u62"},
    "082a5e708f47421da8a73584f56193dd":{
      "scriptId":"u63"},
    "97056cc8bac14cfb8fb4e991bf66ec82":{
      "scriptId":"u64"},
    "d14b5a67944d4473a5af097c8c583942":{
      "scriptId":"u65"},
    "dcf5386f97d34670a614b69925d70337":{
      "scriptId":"u66"},
    "2879caedb0394bd0adaa7a66ae29a123":{
      "scriptId":"u67"},
    "6cbbf917308e42d8870bf39bdc1f9285":{
      "scriptId":"u68"},
    "e5cbbc202cc24af8a4e5fc628f740af5":{
      "scriptId":"u69"},
    "9418b7e550cb4e0ea255899b8db5df2d":{
      "scriptId":"u70"},
    "16f669a6a2f6447b835ae8c30557285c":{
      "scriptId":"u71"},
    "635a5858f5c74459ac90643af0ff3523":{
      "scriptId":"u72"},
    "24fdd19fff084c0494b17e65ad8cfaf5":{
      "scriptId":"u73"},
    "5756254e99ed462487080c0701d03e73":{
      "scriptId":"u74"},
    "c658c3067bad4812bbccf38ec64079da":{
      "scriptId":"u75"},
    "8f2794fc67554a30b76eade11d071ec0":{
      "scriptId":"u76"},
    "7022895d654d49f89346944d3451ebeb":{
      "scriptId":"u77"},
    "d793faf520d145c38caa23f3120ccae7":{
      "scriptId":"u78"},
    "2b7e5cb6a500432ab00d8c0be1de0131":{
      "scriptId":"u79"},
    "e56e46ec14eb44d0ac15438c9e5333ce":{
      "scriptId":"u80"},
    "183518857561464e9187628145e2f47d":{
      "scriptId":"u81"},
    "a3dbe51d56114a18bdfd69aeea5c5e62":{
      "scriptId":"u82"},
    "45f21bde638e4f719b3348cae9ef5601":{
      "scriptId":"u83"},
    "6aeed972eabf48de8f0bbe8c30231497":{
      "scriptId":"u84"},
    "8aefd88c34fc467486a0343f5fa8afe6":{
      "scriptId":"u85"},
    "0c10c978b337465eae38634f57d52f02":{
      "scriptId":"u86"},
    "cd58bd81b8c847d99afbd7fde8743d95":{
      "scriptId":"u87"},
    "8fd4edc1944447c4b09dd4e1390a63f7":{
      "scriptId":"u88"},
    "b5ed2e8ff9b14b24bc88fcfd7340ce18":{
      "scriptId":"u89"},
    "1075b67f5a5f4859adfa6226ba9a8840":{
      "scriptId":"u90"},
    "3e1071df2cc248d4bac15dac5963ff80":{
      "scriptId":"u91"},
    "65c674bc395e4154a14840eac5abcac1":{
      "scriptId":"u92"},
    "210dd600ef854768a5f1552c1b1f6f83":{
      "scriptId":"u93"},
    "21b745953f8846da9b2858b85140d311":{
      "scriptId":"u94"}}});