$axure.loadCurrentPage({
  "url":"发布.html",
  "generationDate":new Date(1407487650187.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9585fdf38d6434ba5ea3500ba4bfe15",
    "type":"Axure:Page",
    "name":"发布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8d90dbeab8c34583b97c9014218cebc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "verticalAlignment":"top",
            "size":{
              "width":1616,
              "height":1989}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ac6de49cbc54b42aaa7886c1f49b635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"top",
                "size":{
                  "width":1616,
                  "height":1989}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布/u0.png"}},
{
          "id":"07b6666f164c4994963f2bae4fc46b24",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "location":{
              "x":470,
              "y":247},
            "size":{
              "width":390,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"b86a6aab74f94f84885dac01268d1a54",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "location":{
              "x":470,
              "y":320},
            "size":{
              "width":390,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"30ead93297d147c6b8c596b23901de73",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "location":{
              "x":470,
              "y":390},
            "size":{
              "width":390,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"0c1545e214294eb3b0681e50c270f2de",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "location":{
              "x":920,
              "y":1270},
            "size":{
              "width":390,
              "height":190}},
          "adaptiveStyles":{
}},
{
          "id":"172e284365c54e20a6abea96f2fcdb75",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":1075},
            "size":{
              "width":140,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a999fa45baee460eb1bd9dc11ee3b532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":930,
                  "y":1075},
                "size":{
                  "width":140,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58348e79b41a40d19ab0b78f2db5517d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":1127},
            "size":{
              "width":140,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"630bb54c294d42279f889410d82e89b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":930,
                  "y":1127},
                "size":{
                  "width":140,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc0577d7e0cc4cd4907fe0d056985de4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1263,
              "y":774},
            "size":{
              "width":47,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d8d0ecb1b76485cbbbad1ec7d0f5556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1263,
                  "y":774},
                "size":{
                  "width":47,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94582af6a18141489eabcab6b3968db0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "location":{
              "x":331,
              "y":491},
            "size":{
              "width":520,
              "height":1099}},
          "adaptiveStyles":{
},
          "placeholderText":"请在此处输入您的内容"},
{
          "id":"ce0b943ea72646d4931d7be23962056a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1038,
              "y":1546},
            "size":{
              "width":172,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00c9a6f2ec8143dabf40275c9fc2b3ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1038,
                  "y":1546},
                "size":{
                  "width":172,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9a149089a2948e0a9b36f7ec1c6556e",
          "label":"近期活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22fed0e66dea406f8d9b5ba4598dc9de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 近期活动",
                      "target":{
                        "targetType":"page",
                        "url":"近期活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdca859fc0fa416296016bc4ccadcb2d",
          "label":"活动回顾",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":526,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"612a0a54065c444f8cce2fbc3f0e5546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":526,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动回顾",
                      "target":{
                        "targetType":"page",
                        "url":"活动回顾.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8400c4a7cb56418aadbc12558dd856a5",
          "label":"放映间",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"affb1fdfae874ef2827c930d47f932e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 放映间",
                      "target":{
                        "targetType":"page",
                        "url":"放映间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfc095c29d3d42078a6cab3cb194e270",
          "label":"品牌活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f34d5f3bcc0e485a8684c2f3766776d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":776,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌活动",
                      "target":{
                        "targetType":"page",
                        "url":"品牌活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da81e659bc9943f6b70da9cf61018e33",
          "label":"投票专区",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":896,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cebd064677d4d83a7fd8348b72dd2ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":896,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 投票专区",
                      "target":{
                        "targetType":"page",
                        "url":"投票专区.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66ffb5e84f454d1f8a13029fe3888be6",
          "label":"发布活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1210,
              "y":147},
            "size":{
              "width":90,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"473f672c610f4f3d885abbd17dc8f83a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1210,
                  "y":147},
                "size":{
                  "width":90,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布",
                      "target":{
                        "targetType":"page",
                        "url":"发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7eb1a37ec88048119cf7f23eecbab7e8",
          "label":"home",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":136},
            "size":{
              "width":56,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7215c49c6aa84526bc538fe59300e23a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":136},
                "size":{
                  "width":56,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93497552f1024954aedc9ffc85ff83c7",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":660,
              "y":468},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"49120e8e6e7f4815b3e07967d2939074",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":650,
              "y":554},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"fdb341ef78834e8b889f7459e22ff234",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":660},
            "size":{
              "width":192,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32eae265d52a47e3a282c539fb31d641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":660},
                "size":{
                  "width":192,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["93497552f1024954aedc9ffc85ff83c7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["49120e8e6e7f4815b3e07967d2939074"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea6b52b0c34c402e80b51350a27f2db3",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1162,
              "y":146},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"440d18321405491fbc4fbf0130c45e75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1162,
                  "y":146},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 密码,<br>用户名,<br>登陆框",
                      "objectsToFades":[{
                          "objectPath":["16dc65311af44db5ae6a685d71f4630e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1de59c785ee44f2fa0b320781af7b674"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["324d8e163919423296ff40c1b7610195"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa169d29e44f428884c2cae7ed44fe3d",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1152,
              "y":370},
            "size":{
              "width":58,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3014f0f2a3c24e8198df06f2eef1b71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1152,
                  "y":370},
                "size":{
                  "width":58,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["93497552f1024954aedc9ffc85ff83c7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["49120e8e6e7f4815b3e07967d2939074"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"324d8e163919423296ff40c1b7610195",
          "label":"登陆框",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":1616,
              "height":3044},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9b05d5f56a449a4bb7f665400599403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":1616,
                  "height":3044},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/登陆框_u102.png"}},
{
          "id":"1de59c785ee44f2fa0b320781af7b674",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":660,
              "y":468},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"16dc65311af44db5ae6a685d71f4630e",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":650,
              "y":554},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"77c7746328fc40b8b79a85d321e2bb20",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":660},
            "size":{
              "width":192,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"590205a515194f3693f89efe47556c47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":660},
                "size":{
                  "width":192,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["324d8e163919423296ff40c1b7610195"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1de59c785ee44f2fa0b320781af7b674"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["16dc65311af44db5ae6a685d71f4630e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29fb2bc8df6849269f1740b645697d47",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1152,
              "y":370},
            "size":{
              "width":58,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bad8391b83644f6b03e66c351e051bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1152,
                  "y":370},
                "size":{
                  "width":58,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["324d8e163919423296ff40c1b7610195"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["1de59c785ee44f2fa0b320781af7b674"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["16dc65311af44db5ae6a685d71f4630e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8d90dbeab8c34583b97c9014218cebc9":{
      "scriptId":"u0"},
    "1ac6de49cbc54b42aaa7886c1f49b635":{
      "scriptId":"u1"},
    "07b6666f164c4994963f2bae4fc46b24":{
      "scriptId":"u2"},
    "b86a6aab74f94f84885dac01268d1a54":{
      "scriptId":"u3"},
    "30ead93297d147c6b8c596b23901de73":{
      "scriptId":"u4"},
    "0c1545e214294eb3b0681e50c270f2de":{
      "scriptId":"u5"},
    "172e284365c54e20a6abea96f2fcdb75":{
      "scriptId":"u6"},
    "a999fa45baee460eb1bd9dc11ee3b532":{
      "scriptId":"u7"},
    "58348e79b41a40d19ab0b78f2db5517d":{
      "scriptId":"u8"},
    "630bb54c294d42279f889410d82e89b3":{
      "scriptId":"u9"},
    "bc0577d7e0cc4cd4907fe0d056985de4":{
      "scriptId":"u10"},
    "9d8d0ecb1b76485cbbbad1ec7d0f5556":{
      "scriptId":"u11"},
    "94582af6a18141489eabcab6b3968db0":{
      "scriptId":"u12"},
    "ce0b943ea72646d4931d7be23962056a":{
      "scriptId":"u13"},
    "00c9a6f2ec8143dabf40275c9fc2b3ba":{
      "scriptId":"u14"},
    "f9a149089a2948e0a9b36f7ec1c6556e":{
      "scriptId":"u15"},
    "22fed0e66dea406f8d9b5ba4598dc9de":{
      "scriptId":"u16"},
    "fdca859fc0fa416296016bc4ccadcb2d":{
      "scriptId":"u17"},
    "612a0a54065c444f8cce2fbc3f0e5546":{
      "scriptId":"u18"},
    "8400c4a7cb56418aadbc12558dd856a5":{
      "scriptId":"u19"},
    "affb1fdfae874ef2827c930d47f932e9":{
      "scriptId":"u20"},
    "dfc095c29d3d42078a6cab3cb194e270":{
      "scriptId":"u21"},
    "f34d5f3bcc0e485a8684c2f3766776d0":{
      "scriptId":"u22"},
    "da81e659bc9943f6b70da9cf61018e33":{
      "scriptId":"u23"},
    "9cebd064677d4d83a7fd8348b72dd2ef":{
      "scriptId":"u24"},
    "66ffb5e84f454d1f8a13029fe3888be6":{
      "scriptId":"u25"},
    "473f672c610f4f3d885abbd17dc8f83a":{
      "scriptId":"u26"},
    "7eb1a37ec88048119cf7f23eecbab7e8":{
      "scriptId":"u27"},
    "7215c49c6aa84526bc538fe59300e23a":{
      "scriptId":"u28"},
    "93497552f1024954aedc9ffc85ff83c7":{
      "scriptId":"u29"},
    "49120e8e6e7f4815b3e07967d2939074":{
      "scriptId":"u30"},
    "fdb341ef78834e8b889f7459e22ff234":{
      "scriptId":"u31"},
    "32eae265d52a47e3a282c539fb31d641":{
      "scriptId":"u32"},
    "ea6b52b0c34c402e80b51350a27f2db3":{
      "scriptId":"u33"},
    "440d18321405491fbc4fbf0130c45e75":{
      "scriptId":"u34"},
    "fa169d29e44f428884c2cae7ed44fe3d":{
      "scriptId":"u35"},
    "3014f0f2a3c24e8198df06f2eef1b71a":{
      "scriptId":"u36"},
    "324d8e163919423296ff40c1b7610195":{
      "scriptId":"u37"},
    "f9b05d5f56a449a4bb7f665400599403":{
      "scriptId":"u38"},
    "1de59c785ee44f2fa0b320781af7b674":{
      "scriptId":"u39"},
    "16dc65311af44db5ae6a685d71f4630e":{
      "scriptId":"u40"},
    "77c7746328fc40b8b79a85d321e2bb20":{
      "scriptId":"u41"},
    "590205a515194f3693f89efe47556c47":{
      "scriptId":"u42"},
    "29fb2bc8df6849269f1740b645697d47":{
      "scriptId":"u43"},
    "7bad8391b83644f6b03e66c351e051bb":{
      "scriptId":"u44"}}});