$axure.loadCurrentPage({
  "url":"放映间.html",
  "generationDate":new Date(1407487648662.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b945d236aa0414fb9c43ad5c0beb75b",
    "type":"Axure:Page",
    "name":"放映间",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bf580da9d5d946b18c5be4409f48a740",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1616,
              "height":1989}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a68954f44a9f4ae2b437ef61612909a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1616,
                  "height":1989}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/放映间/u0.png"}},
{
          "id":"7e73a3bc34174d9fbfbd4b30e8bbf637",
          "label":"近期活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e9c7b3d3d714da2a8f024992ddced2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 近期活动",
                      "target":{
                        "targetType":"page",
                        "url":"近期活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea2f4af859cb49c5bcdabd4b5203a672",
          "label":"活动回顾",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":526,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a911245abe434f5c98f0a39026ae8697",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":526,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动回顾",
                      "target":{
                        "targetType":"page",
                        "url":"活动回顾.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"417817e5dbb94e30b5ed55e843e08901",
          "label":"放映间",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":656,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"917df5e4df6c4b809a9472adfa78993f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":656,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 放映间",
                      "target":{
                        "targetType":"page",
                        "url":"放映间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2d91a81352c48d98960ce41408f0655",
          "label":"品牌活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":776,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"569073e0e9ca4e5fb58ec22107cbf9dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":776,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌活动",
                      "target":{
                        "targetType":"page",
                        "url":"品牌活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbbc07eccf984be4894c2fe6ebcedd7c",
          "label":"投票专区",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":896,
              "y":136},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5eb0671d85943248e39163cda6d17fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":896,
                  "y":136},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 投票专区",
                      "target":{
                        "targetType":"page",
                        "url":"投票专区.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5c2b7a115ba4e9eb21a25051bf4259c",
          "label":"发布活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1210,
              "y":147},
            "size":{
              "width":90,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62adc7c004d84c148b55205de446524b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1210,
                  "y":147},
                "size":{
                  "width":90,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布",
                      "target":{
                        "targetType":"page",
                        "url":"发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6dd3ece7bbc241d88ade6fd0bde36a17",
          "label":"home",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":136},
            "size":{
              "width":56,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e11c0bf278749d49a717f490ded9674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":136},
                "size":{
                  "width":56,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d9aa5fe50124eb68bb40eb774a3add9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":857,
              "y":303},
            "size":{
              "width":443,
              "height":307}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef30ff3bdece4253961cb6ae564c22c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":857,
                  "y":303},
                "size":{
                  "width":443,
                  "height":307}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1259c27577274e249853f535577815ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":700},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afcfc59e11014c2a9340546c1db89281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":700},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"378fc2a5992c4898b8e47f5d36637ed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1094,
              "y":910},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e168943a8b9b4001ad79575893653991",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1094,
                  "y":910},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbc2781fa5c94a6791ce8b17d1a2176c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":845,
              "y":917},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7edfb97de7074e5f9596d7882d941ccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":845,
                  "y":917},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c523f9cf2edb4c969090b1a878409371",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":615,
              "y":709},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45fab13783f248f69adb351e7a8b820f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":615,
                  "y":709},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8711a4bf88a40649a35ba1186e4bc12",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":404},
            "size":{
              "width":330,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a80d8fedf2340f4af846371988b793c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":404},
                "size":{
                  "width":330,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a33af91a8174465a9469a4f54f06e99",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":846,
              "y":1248},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68cbaccc3dd34b77a96e126a60f9fa98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":846,
                  "y":1248},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bde7aa85bff4f2ea8cc7270251fd77b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":846,
              "y":1460},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b86072dad8f7428093eee5818d1e1e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":846,
                  "y":1460},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4833ab97836c46d6b3abdbce865b7fe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":335},
            "size":{
              "width":330,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4063012834345f19b06b553568cd5ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":384,
                  "y":335},
                "size":{
                  "width":330,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4c12982f24449beaa9353806d0e8c97",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":371},
            "size":{
              "width":330,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fc1e60043f74d55a9d0bd24926f1da4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":384,
                  "y":371},
                "size":{
                  "width":330,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"486047d0c9924595ba4bd37a3688a93e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":607,
              "y":919},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccfe62e307594c2e9310a6d5abc023f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":607,
                  "y":919},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"710f4c62eb3c4fca8b4cd7e419da8392",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":709},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fda62a800664ea3919222454ab7af20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":709},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb696411e2ba445180f59e825d624e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":919},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba7f922e60d345a9a5dffb9f27f0edff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":919},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"340c4f0b2080488d9062793019a491e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1087,
              "y":709},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee3e3b597654b7db38a9d9c41ffa25c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1087,
                  "y":709},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2405f202cae41c3b7ea9a823769819d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1087,
              "y":1248},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a55d0be70d4141a92b71ef04fc9503",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1087,
                  "y":1248},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa04327fff2b4e9bb5567c23ea688b30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":607,
              "y":1248},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07700c7507cf4f3ebc47f2463c42c568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":607,
                  "y":1248},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"159050cb95104e7c8dec2bf4b3fa443e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1248},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"819ba4fbf3ee49a1b2c764e1847f0397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":1248},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e5202a7e5d44f0e84da013de8620d10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1460},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9574d729246d4ad2a03431a4f07f3903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":1460},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0a7b16d3a744ce389f101a6f3e42de8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":607,
              "y":1460},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8853a02d397e4d1cbc5aedb8bac10917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":607,
                  "y":1460},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2f5a2fd2f02423a8839b3d6b9504de3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1087,
              "y":1460},
            "size":{
              "width":193,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761689625aa44f0ea0106f5e80818ad9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1087,
                  "y":1460},
                "size":{
                  "width":193,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体播放页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体播放页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d965eb47cc64b0997db81d201ce5366",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1162,
              "y":146},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89680b70c1be49a88df6a8b2afe2442d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1162,
                  "y":146},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 密码,<br>用户名,<br>登陆框",
                      "objectsToFades":[{
                          "objectPath":["a6af9ea00d25469680105f1a2ed8114e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["26452d8c55364d618156ce92e0a63146"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0933601c6a434045bc6e50975d13c3eb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0933601c6a434045bc6e50975d13c3eb",
          "label":"登陆框",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":1616,
              "height":3044},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"233a07477c7c4f2eb0856e7c240875b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":1616,
                  "height":3044},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/登陆框_u102.png"}},
{
          "id":"26452d8c55364d618156ce92e0a63146",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":661,
              "y":469},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"a6af9ea00d25469680105f1a2ed8114e",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":651,
              "y":555},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"381e815bd354465dbc277d2713f663d5",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":false,
          "style":{
            "location":{
              "x":715,
              "y":661},
            "size":{
              "width":192,
              "height":65},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42c41cf303a8497d9591fffbacf79cd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":715,
                  "y":661},
                "size":{
                  "width":192,
                  "height":65},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["0933601c6a434045bc6e50975d13c3eb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["26452d8c55364d618156ce92e0a63146"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a6af9ea00d25469680105f1a2ed8114e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5d131eb5af84818a48767078d6f336c",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":false,
          "style":{
            "location":{
              "x":1153,
              "y":371},
            "size":{
              "width":58,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b51810df8e948f2b303385a2f709385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":1153,
                  "y":371},
                "size":{
                  "width":58,
                  "height":50},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["0933601c6a434045bc6e50975d13c3eb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["26452d8c55364d618156ce92e0a63146"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a6af9ea00d25469680105f1a2ed8114e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bf580da9d5d946b18c5be4409f48a740":{
      "scriptId":"u0"},
    "a68954f44a9f4ae2b437ef61612909a2":{
      "scriptId":"u1"},
    "7e73a3bc34174d9fbfbd4b30e8bbf637":{
      "scriptId":"u2"},
    "6e9c7b3d3d714da2a8f024992ddced2c":{
      "scriptId":"u3"},
    "ea2f4af859cb49c5bcdabd4b5203a672":{
      "scriptId":"u4"},
    "a911245abe434f5c98f0a39026ae8697":{
      "scriptId":"u5"},
    "417817e5dbb94e30b5ed55e843e08901":{
      "scriptId":"u6"},
    "917df5e4df6c4b809a9472adfa78993f":{
      "scriptId":"u7"},
    "c2d91a81352c48d98960ce41408f0655":{
      "scriptId":"u8"},
    "569073e0e9ca4e5fb58ec22107cbf9dc":{
      "scriptId":"u9"},
    "bbbc07eccf984be4894c2fe6ebcedd7c":{
      "scriptId":"u10"},
    "c5eb0671d85943248e39163cda6d17fa":{
      "scriptId":"u11"},
    "c5c2b7a115ba4e9eb21a25051bf4259c":{
      "scriptId":"u12"},
    "62adc7c004d84c148b55205de446524b":{
      "scriptId":"u13"},
    "6dd3ece7bbc241d88ade6fd0bde36a17":{
      "scriptId":"u14"},
    "2e11c0bf278749d49a717f490ded9674":{
      "scriptId":"u15"},
    "4d9aa5fe50124eb68bb40eb774a3add9":{
      "scriptId":"u16"},
    "ef30ff3bdece4253961cb6ae564c22c6":{
      "scriptId":"u17"},
    "1259c27577274e249853f535577815ea":{
      "scriptId":"u18"},
    "afcfc59e11014c2a9340546c1db89281":{
      "scriptId":"u19"},
    "378fc2a5992c4898b8e47f5d36637ed7":{
      "scriptId":"u20"},
    "e168943a8b9b4001ad79575893653991":{
      "scriptId":"u21"},
    "cbc2781fa5c94a6791ce8b17d1a2176c":{
      "scriptId":"u22"},
    "7edfb97de7074e5f9596d7882d941ccd":{
      "scriptId":"u23"},
    "c523f9cf2edb4c969090b1a878409371":{
      "scriptId":"u24"},
    "45fab13783f248f69adb351e7a8b820f":{
      "scriptId":"u25"},
    "f8711a4bf88a40649a35ba1186e4bc12":{
      "scriptId":"u26"},
    "4a80d8fedf2340f4af846371988b793c":{
      "scriptId":"u27"},
    "8a33af91a8174465a9469a4f54f06e99":{
      "scriptId":"u28"},
    "68cbaccc3dd34b77a96e126a60f9fa98":{
      "scriptId":"u29"},
    "4bde7aa85bff4f2ea8cc7270251fd77b":{
      "scriptId":"u30"},
    "b86072dad8f7428093eee5818d1e1e6a":{
      "scriptId":"u31"},
    "4833ab97836c46d6b3abdbce865b7fe6":{
      "scriptId":"u32"},
    "d4063012834345f19b06b553568cd5ad":{
      "scriptId":"u33"},
    "c4c12982f24449beaa9353806d0e8c97":{
      "scriptId":"u34"},
    "8fc1e60043f74d55a9d0bd24926f1da4":{
      "scriptId":"u35"},
    "486047d0c9924595ba4bd37a3688a93e":{
      "scriptId":"u36"},
    "ccfe62e307594c2e9310a6d5abc023f0":{
      "scriptId":"u37"},
    "710f4c62eb3c4fca8b4cd7e419da8392":{
      "scriptId":"u38"},
    "1fda62a800664ea3919222454ab7af20":{
      "scriptId":"u39"},
    "fb696411e2ba445180f59e825d624e37":{
      "scriptId":"u40"},
    "ba7f922e60d345a9a5dffb9f27f0edff":{
      "scriptId":"u41"},
    "340c4f0b2080488d9062793019a491e1":{
      "scriptId":"u42"},
    "0ee3e3b597654b7db38a9d9c41ffa25c":{
      "scriptId":"u43"},
    "b2405f202cae41c3b7ea9a823769819d":{
      "scriptId":"u44"},
    "54a55d0be70d4141a92b71ef04fc9503":{
      "scriptId":"u45"},
    "fa04327fff2b4e9bb5567c23ea688b30":{
      "scriptId":"u46"},
    "07700c7507cf4f3ebc47f2463c42c568":{
      "scriptId":"u47"},
    "159050cb95104e7c8dec2bf4b3fa443e":{
      "scriptId":"u48"},
    "819ba4fbf3ee49a1b2c764e1847f0397":{
      "scriptId":"u49"},
    "3e5202a7e5d44f0e84da013de8620d10":{
      "scriptId":"u50"},
    "9574d729246d4ad2a03431a4f07f3903":{
      "scriptId":"u51"},
    "b0a7b16d3a744ce389f101a6f3e42de8":{
      "scriptId":"u52"},
    "8853a02d397e4d1cbc5aedb8bac10917":{
      "scriptId":"u53"},
    "a2f5a2fd2f02423a8839b3d6b9504de3":{
      "scriptId":"u54"},
    "761689625aa44f0ea0106f5e80818ad9":{
      "scriptId":"u55"},
    "1d965eb47cc64b0997db81d201ce5366":{
      "scriptId":"u56"},
    "89680b70c1be49a88df6a8b2afe2442d":{
      "scriptId":"u57"},
    "0933601c6a434045bc6e50975d13c3eb":{
      "scriptId":"u58"},
    "233a07477c7c4f2eb0856e7c240875b1":{
      "scriptId":"u59"},
    "26452d8c55364d618156ce92e0a63146":{
      "scriptId":"u60"},
    "a6af9ea00d25469680105f1a2ed8114e":{
      "scriptId":"u61"},
    "381e815bd354465dbc277d2713f663d5":{
      "scriptId":"u62"},
    "42c41cf303a8497d9591fffbacf79cd1":{
      "scriptId":"u63"},
    "d5d131eb5af84818a48767078d6f336c":{
      "scriptId":"u64"},
    "4b51810df8e948f2b303385a2f709385":{
      "scriptId":"u65"}}});