$axure.loadCurrentPage({
  "url":"活动回顾.html",
  "generationDate":new Date(1407487648260.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f4c53bf8f63e41978a6d4f0661312140",
    "type":"Axure:Page",
    "name":"活动回顾",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"63395990dba54bacbc2b3cd0a0f93d72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1616,
              "height":1706}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01b2190f6a4480aa51b20559ca7c37b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1616,
                  "height":1706}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动回顾/u0.png"}},
{
          "id":"2d142eb293c048df9ec4ae9e532a8e77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "mouseDown":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":420,
              "y":354},
            "size":{
              "width":70,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42c57b48fcf2463f883ba8fec129d77d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "mouseDown":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":420,
                  "y":354},
                "size":{
                  "width":70,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动回顾/u2.png",
            "mouseOver~":"images/活动回顾/u2_mouseOver.png",
            "mouseDown~":"images/活动回顾/u2_mouseDown.png"}},
{
          "id":"c9c553b3fe144f03ba34ede18632254e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "mouseDown":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":490,
              "y":354},
            "size":{
              "width":70,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7159ce3c3f04695bed8574ae641a69d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "mouseDown":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":490,
                  "y":354},
                "size":{
                  "width":70,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动回顾/u2.png",
            "mouseOver~":"images/活动回顾/u2_mouseOver.png",
            "mouseDown~":"images/活动回顾/u2_mouseDown.png"}},
{
          "id":"8cc4b441e7e24510a730f0bb7980b653",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "mouseDown":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":560,
              "y":354},
            "size":{
              "width":70,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1180a55b0b774c8cb41d36cc8c84e406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "mouseDown":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":560,
                  "y":354},
                "size":{
                  "width":70,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动回顾/u2.png",
            "mouseOver~":"images/活动回顾/u2_mouseOver.png",
            "mouseDown~":"images/活动回顾/u2_mouseDown.png"}},
{
          "id":"30c6e0818b1e42fbae9e3fa8769bf5c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "mouseDown":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":630,
              "y":354},
            "size":{
              "width":80,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aef7583c1c14dc9a9c58e2962388790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "mouseDown":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":630,
                  "y":354},
                "size":{
                  "width":80,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动回顾/u8.png",
            "mouseOver~":"images/活动回顾/u8_mouseOver.png",
            "mouseDown~":"images/活动回顾/u8_mouseDown.png"}},
{
          "id":"5cbe1fe043794054836763941d1d00ae",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":370},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8d5f30a3c7a8486d88101ceb75200204",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":392},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8d3cf893a52e42c58ddae79690bb86cc",
          "label":"东校",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":407,
              "y":419},
            "size":{
              "width":550,
              "height":922}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1fc789edcb4b401ebaaced2cd85c8db9",
              "label":"活动回顾1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"028d9ee0516648cb8a50552c99c997ee",
                  "label":"",
                  "parentDynamicPanel":"8d3cf893a52e42c58ddae79690bb86cc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":575,
                      "height":928}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41d089383e294e60a8f6b64623c34a83",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8d3cf893a52e42c58ddae79690bb86cc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":575,
                          "height":928}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/活动回顾/u13.png"}}]},
{
              "id":"19c117de3fcc404da54687d94c8d75da",
              "label":"活动回顾2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6d01659457104af7a8c9ae19c70832af",
                  "label":"",
                  "parentDynamicPanel":"8d3cf893a52e42c58ddae79690bb86cc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":575,
                      "height":928}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57d2983e72c743e58abedb0376229621",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8d3cf893a52e42c58ddae79690bb86cc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":575,
                          "height":928}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/活动回顾/u15.png"}}]},
{
              "id":"dc39b9550d2540fd8387c3689fcf6fa0",
              "label":"活动回顾3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ce6d85493a44425c9886251d0cd40f07",
                  "label":"",
                  "parentDynamicPanel":"8d3cf893a52e42c58ddae79690bb86cc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":575,
                      "height":928}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56c184ee589743a5adb6790f5a14386b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8d3cf893a52e42c58ddae79690bb86cc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":575,
                          "height":928}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/活动回顾/u17.png"}}]}]},
{
          "id":"d93f4c108b2f4d348fe586e6ecaf3bbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":1300},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17db5579d7654828a11c2d11d8e357e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":1300},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 东校 to 活动回顾2",
                      "panelsToStates":[{
                          "panelPath":["8d3cf893a52e42c58ddae79690bb86cc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c277fecb2f794edfa232cc3609dd7a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":1300},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"462d9d84009c4ce3b342a81bf5eed356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":1300},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 东校 to 活动回顾1",
                      "panelsToStates":[{
                          "panelPath":["8d3cf893a52e42c58ddae79690bb86cc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f6cb0fd8e0641fc9e0d1b838d792f5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":1300},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab19ac6a448b4124a3fcd3aa1ffd0048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":1300},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 东校 to 活动回顾3",
                      "panelsToStates":[{
                          "panelPath":["8d3cf893a52e42c58ddae79690bb86cc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3c94891f63845ae9d5c742811d9a8c5",
          "label":"近期活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cbf67efc81b45caae1dd0134b1a66ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 近期活动",
                      "target":{
                        "targetType":"page",
                        "url":"近期活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99e5d3438a5d483ea49c972d642cdf41",
          "label":"活动回顾",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77631e3588024e44a5e4f9b2dfd17468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动回顾",
                      "target":{
                        "targetType":"page",
                        "url":"活动回顾.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1c261fb7aec4648aa0ab481fd8bdab4",
          "label":"放映间",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":658,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cd91e85912e49299eb3dbc71716ae23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":658,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 放映间",
                      "target":{
                        "targetType":"page",
                        "url":"放映间.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"936145b917764c71a38d0430753debb7",
          "label":"品牌活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9032c98de1fc491697fca569e06fefb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 品牌活动",
                      "target":{
                        "targetType":"page",
                        "url":"品牌活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad4232dc966b4da19c98b195c07409a1",
          "label":"投票专区",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":898,
              "y":135},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724838e09a4e450fb12dbd2638d3df3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":898,
                  "y":135},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 投票专区",
                      "target":{
                        "targetType":"page",
                        "url":"投票专区.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5390ecaa22124797b1309d39a7784a67",
          "label":"发布活动",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1212,
              "y":146},
            "size":{
              "width":90,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaa9e74663cd47baa2d218ab9e9e45d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1212,
                  "y":146},
                "size":{
                  "width":90,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布",
                      "target":{
                        "targetType":"page",
                        "url":"发布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dee23e10bb0438c8f1fe20481c07630",
          "label":"home",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":135},
            "size":{
              "width":56,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9001cc5d451245588c4a0c1d65f024bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":135},
                "size":{
                  "width":56,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02d19b32a1504043baf8b4c3e4d393e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":477},
            "size":{
              "width":529,
              "height":203}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e55503461047ca9373a6b20f98aa10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":477},
                "size":{
                  "width":529,
                  "height":203}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"453e09716d1c4e8d9b8c98abf96d7a54",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":717},
            "size":{
              "width":529,
              "height":203}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f247207a7c74138beafaef897fee1f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":717},
                "size":{
                  "width":529,
                  "height":203}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf5a4a3fe4e443d394b62c171bac857e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":967,
              "y":981},
            "size":{
              "width":293,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cac68cc22fb040a7bc0900e1da2e858f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":967,
                  "y":981},
                "size":{
                  "width":293,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf03bbec9b8b45cba3ce663b1f02783b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":967,
              "y":938},
            "size":{
              "width":293,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a76b336a7cd545c993b74d5d74456d5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":967,
                  "y":938},
                "size":{
                  "width":293,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"910a4a4a333843a7a035fd3ce217b3a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":967,
              "y":895},
            "size":{
              "width":293,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00139de5b34404a93c30ee159f49465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":967,
                  "y":895},
                "size":{
                  "width":293,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba61fc43527a4b4aabd1085dc2d8a580",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":963,
              "y":858},
            "size":{
              "width":293,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48f66c0c692a40a9b468ad179148e788",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":963,
                  "y":858},
                "size":{
                  "width":293,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fffe371bbeb444a9969391ce9536c35d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":967,
              "y":815},
            "size":{
              "width":293,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"751f3dc8f86f4c6f8934a69889f6d58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":967,
                  "y":815},
                "size":{
                  "width":293,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a66e3bcb4c664b76b2f8033b0d8f477f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":718},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f87f6491efd45f38ea8fab0d7bafc30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":718},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b8f81174d944e0d981352a9dad4b7e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":685},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d1c4162b86e438abf8c2de30414728b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":685},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1bb8f1f455842f49befb5d9858dcf52",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":660},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0c1d274e284edb9aa3d86ed21c03c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":660},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b42a3ab21d44e6b907b67aca4070ceb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":627},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd0fa8263c2d4e2c94b5b51cff66887c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":627},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"101e3f232f674c4895c7caf5aac3c120",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":594},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1fdf6ec4d2f48f2bc36dfd7ce0d6aed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":594},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5815d490ddd44384aa244e20cb05ed88",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":561},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b858af8784a74ba9ae3bc3a723f4a23f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":561},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67c5067d7ebd40a0882a1494d0c5cf7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":537},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed86d2aad37148b0ae747c5c8a7a7149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":537},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"980443a06ac04f179b621e92fb0a684b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":510},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d78025502fac4113b3d967dfa5f91f76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":510},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f426cbbf3634ed88bd222bbb326b9bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":477},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"740699d1ca604c8e8e560a4008c16a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":477},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fed5e0f99fbc4a9a8b5c9ff5ef2f369a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":454},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3a72b1130b4f97ba9f2bf4ad0fc0eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":454},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17f30ec452314d7aa788d0192a6d4c72",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":430},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6595c8290aeb4cd88da0c15180ed5d36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":430},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8bf7b08fecd4c6e8cd680098b67c781",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":403},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58332fc5aa11433b8b9365cda6d7bf07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":403},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b99be44627ab4ece95ed95f6890cf963",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":370},
            "size":{
              "width":223,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b9ed294b71b453ca78780e473402d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":977,
                  "y":370},
                "size":{
                  "width":223,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 具体活动页面",
                      "target":{
                        "targetType":"page",
                        "url":"具体活动页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88f66dd0a7a949dba1a765db9f46a6d8",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1162,
              "y":146},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0056acc8cd74ed6b7f0150c3f8be85f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1162,
                  "y":146},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 密码,<br>用户名,<br>登陆框",
                      "objectsToFades":[{
                          "objectPath":["9f3f03a79e344031b579220aa265fb65"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["df67e0f198c94d08ad45ea9c6309a01c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["cd85ac9a5813496e9502f1cabcef0371"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd85ac9a5813496e9502f1cabcef0371",
          "label":"登陆框",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "size":{
              "width":1616,
              "height":3044},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c39b61839d849f78808ec7501f25a4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "size":{
                  "width":1616,
                  "height":3044},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/登陆框_u102.png"}},
{
          "id":"df67e0f198c94d08ad45ea9c6309a01c",
          "label":"用户名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":660,
              "y":468},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"9f3f03a79e344031b579220aa265fb65",
          "label":"密码",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5C5C5C,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":650,
              "y":554},
            "size":{
              "width":395,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"0c490ac228524df4b39dc7d9fe6c6526",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":660},
            "size":{
              "width":192,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94ed18b7cd341df99adb0f955f54408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":660},
                "size":{
                  "width":192,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["cd85ac9a5813496e9502f1cabcef0371"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["df67e0f198c94d08ad45ea9c6309a01c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9f3f03a79e344031b579220aa265fb65"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0846f89f28b541a2a38d82bd4471fa74",
          "label":"登陆",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1152,
              "y":370},
            "size":{
              "width":58,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0ee744f20db4016920b4218b63652fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1152,
                  "y":370},
                "size":{
                  "width":58,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 登陆框,<br>用户名,<br>密码",
                      "objectsToFades":[{
                          "objectPath":["cd85ac9a5813496e9502f1cabcef0371"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["df67e0f198c94d08ad45ea9c6309a01c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9f3f03a79e344031b579220aa265fb65"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d9e571f3eea4ee49bb2e250a6d7d10b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "mouseDown":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":710,
              "y":354},
            "size":{
              "width":80,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9adc48fbd9f843e5a2e1a5f6ee7e0458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "mouseDown":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":710,
                  "y":354},
                "size":{
                  "width":80,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动回顾/u8.png",
            "mouseOver~":"images/活动回顾/u8_mouseOver.png",
            "mouseDown~":"images/活动回顾/u8_mouseDown.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "63395990dba54bacbc2b3cd0a0f93d72":{
      "scriptId":"u0"},
    "c01b2190f6a4480aa51b20559ca7c37b":{
      "scriptId":"u1"},
    "2d142eb293c048df9ec4ae9e532a8e77":{
      "scriptId":"u2"},
    "42c57b48fcf2463f883ba8fec129d77d":{
      "scriptId":"u3"},
    "c9c553b3fe144f03ba34ede18632254e":{
      "scriptId":"u4"},
    "c7159ce3c3f04695bed8574ae641a69d":{
      "scriptId":"u5"},
    "8cc4b441e7e24510a730f0bb7980b653":{
      "scriptId":"u6"},
    "1180a55b0b774c8cb41d36cc8c84e406":{
      "scriptId":"u7"},
    "30c6e0818b1e42fbae9e3fa8769bf5c9":{
      "scriptId":"u8"},
    "4aef7583c1c14dc9a9c58e2962388790":{
      "scriptId":"u9"},
    "5cbe1fe043794054836763941d1d00ae":{
      "scriptId":"u10"},
    "8d5f30a3c7a8486d88101ceb75200204":{
      "scriptId":"u11"},
    "8d3cf893a52e42c58ddae79690bb86cc":{
      "scriptId":"u12"},
    "028d9ee0516648cb8a50552c99c997ee":{
      "scriptId":"u13"},
    "41d089383e294e60a8f6b64623c34a83":{
      "scriptId":"u14"},
    "6d01659457104af7a8c9ae19c70832af":{
      "scriptId":"u15"},
    "57d2983e72c743e58abedb0376229621":{
      "scriptId":"u16"},
    "ce6d85493a44425c9886251d0cd40f07":{
      "scriptId":"u17"},
    "56c184ee589743a5adb6790f5a14386b":{
      "scriptId":"u18"},
    "d93f4c108b2f4d348fe586e6ecaf3bbe":{
      "scriptId":"u19"},
    "17db5579d7654828a11c2d11d8e357e5":{
      "scriptId":"u20"},
    "c277fecb2f794edfa232cc3609dd7a1b":{
      "scriptId":"u21"},
    "462d9d84009c4ce3b342a81bf5eed356":{
      "scriptId":"u22"},
    "9f6cb0fd8e0641fc9e0d1b838d792f5f":{
      "scriptId":"u23"},
    "ab19ac6a448b4124a3fcd3aa1ffd0048":{
      "scriptId":"u24"},
    "e3c94891f63845ae9d5c742811d9a8c5":{
      "scriptId":"u25"},
    "2cbf67efc81b45caae1dd0134b1a66ff":{
      "scriptId":"u26"},
    "99e5d3438a5d483ea49c972d642cdf41":{
      "scriptId":"u27"},
    "77631e3588024e44a5e4f9b2dfd17468":{
      "scriptId":"u28"},
    "c1c261fb7aec4648aa0ab481fd8bdab4":{
      "scriptId":"u29"},
    "6cd91e85912e49299eb3dbc71716ae23":{
      "scriptId":"u30"},
    "936145b917764c71a38d0430753debb7":{
      "scriptId":"u31"},
    "9032c98de1fc491697fca569e06fefb5":{
      "scriptId":"u32"},
    "ad4232dc966b4da19c98b195c07409a1":{
      "scriptId":"u33"},
    "724838e09a4e450fb12dbd2638d3df3a":{
      "scriptId":"u34"},
    "5390ecaa22124797b1309d39a7784a67":{
      "scriptId":"u35"},
    "eaa9e74663cd47baa2d218ab9e9e45d6":{
      "scriptId":"u36"},
    "1dee23e10bb0438c8f1fe20481c07630":{
      "scriptId":"u37"},
    "9001cc5d451245588c4a0c1d65f024bd":{
      "scriptId":"u38"},
    "02d19b32a1504043baf8b4c3e4d393e5":{
      "scriptId":"u39"},
    "a8e55503461047ca9373a6b20f98aa10":{
      "scriptId":"u40"},
    "453e09716d1c4e8d9b8c98abf96d7a54":{
      "scriptId":"u41"},
    "6f247207a7c74138beafaef897fee1f8":{
      "scriptId":"u42"},
    "bf5a4a3fe4e443d394b62c171bac857e":{
      "scriptId":"u43"},
    "cac68cc22fb040a7bc0900e1da2e858f":{
      "scriptId":"u44"},
    "cf03bbec9b8b45cba3ce663b1f02783b":{
      "scriptId":"u45"},
    "a76b336a7cd545c993b74d5d74456d5a":{
      "scriptId":"u46"},
    "910a4a4a333843a7a035fd3ce217b3a6":{
      "scriptId":"u47"},
    "e00139de5b34404a93c30ee159f49465":{
      "scriptId":"u48"},
    "ba61fc43527a4b4aabd1085dc2d8a580":{
      "scriptId":"u49"},
    "48f66c0c692a40a9b468ad179148e788":{
      "scriptId":"u50"},
    "fffe371bbeb444a9969391ce9536c35d":{
      "scriptId":"u51"},
    "751f3dc8f86f4c6f8934a69889f6d58c":{
      "scriptId":"u52"},
    "a66e3bcb4c664b76b2f8033b0d8f477f":{
      "scriptId":"u53"},
    "2f87f6491efd45f38ea8fab0d7bafc30":{
      "scriptId":"u54"},
    "0b8f81174d944e0d981352a9dad4b7e9":{
      "scriptId":"u55"},
    "5d1c4162b86e438abf8c2de30414728b":{
      "scriptId":"u56"},
    "b1bb8f1f455842f49befb5d9858dcf52":{
      "scriptId":"u57"},
    "ce0c1d274e284edb9aa3d86ed21c03c6":{
      "scriptId":"u58"},
    "9b42a3ab21d44e6b907b67aca4070ceb":{
      "scriptId":"u59"},
    "bd0fa8263c2d4e2c94b5b51cff66887c":{
      "scriptId":"u60"},
    "101e3f232f674c4895c7caf5aac3c120":{
      "scriptId":"u61"},
    "d1fdf6ec4d2f48f2bc36dfd7ce0d6aed":{
      "scriptId":"u62"},
    "5815d490ddd44384aa244e20cb05ed88":{
      "scriptId":"u63"},
    "b858af8784a74ba9ae3bc3a723f4a23f":{
      "scriptId":"u64"},
    "67c5067d7ebd40a0882a1494d0c5cf7b":{
      "scriptId":"u65"},
    "ed86d2aad37148b0ae747c5c8a7a7149":{
      "scriptId":"u66"},
    "980443a06ac04f179b621e92fb0a684b":{
      "scriptId":"u67"},
    "d78025502fac4113b3d967dfa5f91f76":{
      "scriptId":"u68"},
    "3f426cbbf3634ed88bd222bbb326b9bb":{
      "scriptId":"u69"},
    "740699d1ca604c8e8e560a4008c16a78":{
      "scriptId":"u70"},
    "fed5e0f99fbc4a9a8b5c9ff5ef2f369a":{
      "scriptId":"u71"},
    "7a3a72b1130b4f97ba9f2bf4ad0fc0eb":{
      "scriptId":"u72"},
    "17f30ec452314d7aa788d0192a6d4c72":{
      "scriptId":"u73"},
    "6595c8290aeb4cd88da0c15180ed5d36":{
      "scriptId":"u74"},
    "e8bf7b08fecd4c6e8cd680098b67c781":{
      "scriptId":"u75"},
    "58332fc5aa11433b8b9365cda6d7bf07":{
      "scriptId":"u76"},
    "b99be44627ab4ece95ed95f6890cf963":{
      "scriptId":"u77"},
    "0b9ed294b71b453ca78780e473402d08":{
      "scriptId":"u78"},
    "88f66dd0a7a949dba1a765db9f46a6d8":{
      "scriptId":"u79"},
    "c0056acc8cd74ed6b7f0150c3f8be85f":{
      "scriptId":"u80"},
    "cd85ac9a5813496e9502f1cabcef0371":{
      "scriptId":"u81"},
    "4c39b61839d849f78808ec7501f25a4c":{
      "scriptId":"u82"},
    "df67e0f198c94d08ad45ea9c6309a01c":{
      "scriptId":"u83"},
    "9f3f03a79e344031b579220aa265fb65":{
      "scriptId":"u84"},
    "0c490ac228524df4b39dc7d9fe6c6526":{
      "scriptId":"u85"},
    "f94ed18b7cd341df99adb0f955f54408":{
      "scriptId":"u86"},
    "0846f89f28b541a2a38d82bd4471fa74":{
      "scriptId":"u87"},
    "e0ee744f20db4016920b4218b63652fd":{
      "scriptId":"u88"},
    "6d9e571f3eea4ee49bb2e250a6d7d10b":{
      "scriptId":"u89"},
    "9adc48fbd9f843e5a2e1a5f6ee7e0458":{
      "scriptId":"u90"}}});